#CSR_PORTAL
txt_loginUsername="id:authUsername"
txt_loginPassword="id:authPassword"
Btn_Login="id:loginBtn"
green_BanPth="xpath://div[@class='toast-message']"
txt_SearchBox="id:contracts-collection-search-text"
Search_Icon="xpath://mat-icon[@id='']"
Spinner_Pth="xpath://div[@class='ng-star-inserted spinnerWrapperPost']"
Cust_PolNum="id:selected-roles-policy-number-label"
txt_FullN="id:selected-roles-full-name-label"
txt_CustRole="id:selected-roles-role-label"
Aut_Btn="id:authorize-undefined-button"
Aut_PolNum_Lab="id:authorize-sucess-policy-number-label"
Aut_Full_Name="id:authorize-sucess-full-name-label"
Aut_Role="id:authorize-sucess-role-label"
Comp_Code="id:policy-details-company-code-label"
Related_Par_Own="xpath://div[contains(@class,'partyRoleListTable')]//label[text()='Owner']"
Add_Btn="xpath://span[contains(text(),'sidence')]/following::button[1]"
Add_Line1="xpath://input[@placeholder='Address Line 1']"
Save_Btn="xpath://span[text()='SAVE']"
Green_Bann_Mess="xpath://div[@class='ui-growl-message']"
Cls_Btn="id:modal__cross"
Work_Req_Type="id:workRequestHistoryTable_0_Type"
Work_Req_Status="id:workRequestHistoryTable_0_Status"
PhNum_Tab="xpath://div[text()='PHONE NUMBER']"
Ph_Addbtn="xpath://mat-icon[text()='add']"
PhNum_Field="xpath://span[text()='Type']//preceding::input[1][@placeholder='Phone Number']"
Ph_Typ="xpath://mat-select[@placeholder='Type']"
Ph_TypOpt="//span[text()=' WORK CELL']"
Email_Tab="xpath://div[text()='ADDRESSES']//following::div[4]"
Email_Field="xpath://span[text()='Type']//preceding::input[1][@placeholder='Email']"
Email_TypeOpt="//span[text()=' ELEC MAIL']"

#WMA_REGION
WMA_UserName="xpath://input[@type='text']"
WMA_Password="xpath://input[@type='password']"
Sub_Btn="xpath://input[@type='submit']"
Comp_Cde_Drp="xpath://select[@name='mainform:clientRequestCompanyCode']"
Poli_Search="xpath://input[@id='mainform:clientRequestMasterId']"
WMA_Search_Btn="xpath://input[@id='mainform:searchButton']"
WMA_Roles_Tab="xpath://img[@src='/wma/resources/images/tree/roles_in.gif']"
WMA_Owner_Role="xpath://span[text()='Owner']//following::td[1]"
WMA_Update_Party_Btn="xpath://input[@id='mainform:updateParty']"
WMA_Add_Line1="xpath://input[@id='mainform:directoryTransactionDirectoryTransactionTrxSegmentCurrentAddressLine1']"
Demogra_Tab="id:DemographicChange_ID"
wma_PhField="xpath://option[@value='WC' and @selected='selected']//following::input[1]"
wma_EmailField="xpath://option[@value='EM'and @selected='selected']//following::input[1]"
